-- Drop File
-- Autor: Lukas Zainzinger
-- Version: 12.03.2015

DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS segler CASCADE;
DROP TABLE IF EXISTS trainer CASCADE;
DROP TABLE IF EXISTS boot CASCADE;
DROP TABLE IF EXISTS tourenboot CASCADE;
DROP TABLE IF EXISTS sportboot CASCADE;
DROP TABLE IF EXISTS mannschaft CASCADE;
DROP TABLE IF EXISTS regatta CASCADE;
DROP TABLE IF EXISTS wettfahrt CASCADE;
DROP TABLE IF EXISTS bildet CASCADE;
DROP TABLE IF EXISTS erzielt CASCADE;
DROP TABLE IF EXISTS zugewiesen CASCADE;
DROP TABLE IF EXISTS nimmtteil CASCADE;